#!/bin/sh
# =========
# Autostart
# =========
# Start keybindings
sxhkd &

# Start compositor
picom &

# Start polybar

polybar nord &

# Numlock

numlockx &

# Start Dunst (notifications)

dunst &

#start flameshot

flameshot &

#start protonmail-bridge

protonmail-bridge --no-window &

#start nextcloud

nextcloud --background &

# Start polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start mouse
xsetroot -cursor_name left_ptr &

# Set wallpaper
feh --bg-fill /home/tuxflux/Pictures/Wallpapers/Nord/nord_underwater.png &
#feh --bg-fill ~/Pictures/Wallpapers/Ultrawide/nightcity.jpg &

# Start status bar
bash /home/tuxflux/.config/polybar/launch.sh &

# Start toggle script
bash /home/tuxflux/.config/bspwm/toggle.sh &

# Auto Betterlock
xidlehook --not-when-audio --not-when-fullscreen --timer 360 "betterlockscreen -l dim" "" &


# ==========
# Workspaces
# ==========
bspc monitor -d I II III IV V VI VII

# =====
# Tiled
# =====
# Border width
bspc config border_width 2

# Gap between windows
bspc config window_gap 40

# Windows split ratio
bspc config split_ratio 0.5

# Colours
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#88c0d0"
bspc config presel_feedback_color	"#88c0d0"

# =======
# Monocle
# =======
# Monocle mode settings
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle	 true
bspc config single_monocle true
bspc config left_monocle_padding 600
bspc config right_monocle_padding 600
bspc config top_monocle_padding 40
bspc config bottom_monocle_padding 40



# ============
# Window Rules
# ============
bspc rule -a firefox          desktop="^2"
bspc rule -a thunderbird      desktop="^2"
bspc rule -a FeedReader       desktop="^2"
bspc rule -a feedreader       desktop="^2"
bspc rule -a Chromium         desktop="^2"
bspc rule -a telegram-desktop desktop="^3"
bspc rule -a TelegramDesktop  desktop="^3"
bspc rule -a "Tor Browser"    desktop="^2"
bspc rule -a filezilla        desktop="^2"
bspc rule -a Filezilla        desktop="^2"
bspc rule -a Darktable        desktop="^6"
bspc rule -a Gimp             desktop="^6"
bspc rule -a gimp             desktop="^6"
bspc rule -a Inkscape         desktop="^6"
bspc rule -a Lutris           desktop="^4"
bspc rule -a Lutris           desktop="^4"
bspc rule -a Steam            desktop="^4"
bspc rule -a steam            desktop="^4"
bspc rule -a Spotify          desktop="^5"
bspc rule -a spotify          desktop="^5"
bspc rule -a konversation     desktop="^3"


# ==============
# Floating Rules
# ==============

bspc rule -a feh                   state=floating center=true
bspc rule -a Gnome-calculator      state=floating center=true
bspc rule -a Calculator            state=floating center=true
bspc rule -a wow.exe               state=floating center=true
